---
- name: Installation apache2
  apt:
    name: "{{ apache_service }}"
    state: latest

- name: Démarrage apache2
  systemd:
    name: "{{ apache_service }}"
    state: started
    enabled: true
    daemon_reload: true

- name: Modif de apache2.conf
  template:
    src: "{{ apache_jinja }}"
    dest: "{{ apache_conf_file }}"
    mode: 0644