---
- name: Installation apache2
  apt:
    name: "{{ apache_service }}"
    state: latest

- name: Démarrage apache2
  systemd:
    name: "{{ apache_service }}"
    state: started
    enabled: true
    daemon_reload: true

- name: Modif de apache2.conf
  lineinfile:
    path: "{{ apache_conf_file }}"
    regexp: '^ServerAdmin'
    line: 'ServerAdmin test1@fr.clara.net'
  notify:
  - Rédémarrage apache2
