---
- hosts: all
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Update et upgrade apt packages
      apt:
        update_cache: yes
    - name: Installation software-properties-common
      apt:
        name: "{{ spc }}"
    - name: Ajout du repo Suricata
      become: yes
      apt_repository:
        repo: "{{ suricata_repo }}"
        state: present

    - name: Installation de suricata
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        "{{ apt_dependencies }}"

    - name: Modification du fichier de conf Suricata
      template:
        src: "{{ suricata_conf_template }}"
        dest: "{{ suricata_conf_path }}"
        mode: 0644
      
    - name: Generation de /var/lib/suricata/rules
      command: sudo {{ suricata_update_rules }}

    - name: Lancement de Suricata
      systemd:
        name: "{{ suricata_service }}"
        state: started
        enabled: true
        daemon_reload: true
