# ansible-playbook -i ansible_dir/00_inventory.yml --ask-become-pass solutions/Q6/playbook.yml
---
- name: Playbook reprenant les rôles des précédentes questions
  hosts: all
  become: yes
  roles:
    - initial_setup
    - user
    - ssh_key_exchange
    - apache2